# Generated by Django 5.0.6 on 2024-07-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_new_date_portfolio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/images')),
                ('descreaption', models.TextField()),
                ('full_name', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
